[2024-06-06T13:51:20.817+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: test_dag.test_rds_conn manual__2024-06-06T13:51:20.118224+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
