[2024-06-06T12:42:53.098+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: p1_dag.initial_impute manual__2024-06-06T12:42:51.705805+00:00 [queued]>
[2024-06-06T12:42:53.102+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: p1_dag.initial_impute manual__2024-06-06T12:42:51.705805+00:00 [queued]>
[2024-06-06T12:42:53.102+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-06T12:42:53.107+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): initial_impute> on 2024-06-06 12:42:51.705805+00:00
[2024-06-06T12:42:53.110+0000] {standard_task_runner.py:60} INFO - Started process 645 to run task
[2024-06-06T12:42:53.112+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'p1_dag', 'initial_impute', 'manual__2024-06-06T12:42:51.705805+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/path1.py', '--cfg-path', '/tmp/tmpzjsiu1sz']
[2024-06-06T12:42:53.113+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask initial_impute
[2024-06-06T12:42:53.124+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-06T12:42:53.140+0000] {task_command.py:423} INFO - Running <TaskInstance: p1_dag.initial_impute manual__2024-06-06T12:42:51.705805+00:00 [running]> on host da925791f65a
[2024-06-06T12:42:53.173+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='billyin' AIRFLOW_CTX_DAG_ID='p1_dag' AIRFLOW_CTX_TASK_ID='initial_impute' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T12:42:51.705805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T12:42:51.705805+00:00'
[2024-06-06T12:42:53.174+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: initial_impute() missing 1 required positional argument: 'data'
[2024-06-06T12:42:53.177+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=p1_dag, task_id=initial_impute, execution_date=20240606T124251, start_date=20240606T124253, end_date=20240606T124253
[2024-06-06T12:42:53.182+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task initial_impute (initial_impute() missing 1 required positional argument: 'data'; 645)
[2024-06-06T12:42:53.210+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-06T12:42:53.219+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
